# Alt Küme Üzerinde İşlem Yapmak

In [1]:
import numpy as np

In [2]:
a = np.random.randint(10, size=(5,5))
a

array([[7, 8, 6, 2, 5],
       [9, 0, 9, 8, 6],
       [0, 2, 4, 5, 1],
       [5, 7, 3, 1, 2],
       [5, 3, 1, 9, 1]])

In [3]:
alt_kume1 = a[1:4, :]
alt_kume1

array([[9, 0, 9, 8, 6],
       [0, 2, 4, 5, 1],
       [5, 7, 3, 1, 2]])

In [4]:
alt_kume1[0,3] = 555
alt_kume1[1,1] = 666
alt_kume1[2,2]  = 777
alt_kume1[1,4] = 888

In [5]:
alt_kume1

array([[  9,   0,   9, 555,   6],
       [  0, 666,   4,   5, 888],
       [  5,   7, 777,   1,   2]])

In [6]:
a

array([[  7,   8,   6,   2,   5],
       [  9,   0,   9, 555,   6],
       [  0, 666,   4,   5, 888],
       [  5,   7, 777,   1,   2],
       [  5,   3,   1,   9,   1]])

In [7]:
m = np.random.randint(20, size=(5,5))
m

array([[17, 16,  3,  2,  7],
       [19,  1,  0, 10,  1],
       [17,  4,  7, 17, 12],
       [13,  7,  1, 17,  6],
       [12, 18, 14, 16,  0]])

In [8]:
m_alt = m[1:4, 1:4].copy()
m_alt

array([[ 1,  0, 10],
       [ 4,  7, 17],
       [ 7,  1, 17]])

In [9]:
m_alt[1,1] = 878
m_alt[2,1] = 232
m_alt

array([[  1,   0,  10],
       [  4, 878,  17],
       [  7, 232,  17]])

In [10]:
m

array([[17, 16,  3,  2,  7],
       [19,  1,  0, 10,  1],
       [17,  4,  7, 17, 12],
       [13,  7,  1, 17,  6],
       [12, 18, 14, 16,  0]])

In [11]:
main = np.random.randint(30, size=(4,4))
main

array([[17, 15, 25, 28],
       [24,  6,  8, 10],
       [25, 11, 11, 26],
       [10,  9, 23, 21]])

In [12]:
piece = main[1:3, 1:3].copy()
piece

array([[ 6,  8],
       [11, 11]])

In [13]:
piece * 0

array([[0, 0],
       [0, 0]])

In [14]:
piece * 5

array([[30, 40],
       [55, 55]])

In [15]:
piece * 2

array([[12, 16],
       [22, 22]])

In [16]:
(piece / 2).dtype

dtype('float64')

In [17]:
my_list1 = np.random.randint(20, size=(4,4))
my_list1

array([[ 8,  1, 11,  2],
       [13, 16,  3, 14],
       [17, 16,  9,  5],
       [17, 13,  6,  9]])

In [18]:
parca = my_list1[1:3, 1:3]
parca

array([[16,  3],
       [16,  9]])

In [19]:
parca[0,0] = 555
parca

array([[555,   3],
       [ 16,   9]])

In [20]:
parca[0,1] = 666
parca

array([[555, 666],
       [ 16,   9]])

In [21]:
parca[1,0] = 777
parca

array([[555, 666],
       [777,   9]])

In [22]:
parca[1,1] = 888
parca

array([[555, 666],
       [777, 888]])

In [23]:
array = np.random.randint(60, size=(5,5))
array

array([[47, 30, 57, 58, 21],
       [44,  5,  9, 27, 53],
       [27, 49, 27, 47, 26],
       [14, 55, 29,  3, 47],
       [ 3, 26, 59, 15,  0]])

In [24]:
alt_kume = array[1:4, 1:4]
alt_kume

array([[ 5,  9, 27],
       [49, 27, 47],
       [55, 29,  3]])

In [27]:
alt_kume[1,1] = 555
alt_kume

array([[  5,   9,  27],
       [ 49, 555,  47],
       [ 55,  29,   3]])

In [28]:
alt_kume[2,2] = 999
alt_kume

array([[  5,   9,  27],
       [ 49, 555,  47],
       [ 55,  29, 999]])

In [29]:
array

array([[ 47,  30,  57,  58,  21],
       [ 44,   5,   9,  27,  53],
       [ 27,  49, 555,  47,  26],
       [ 14,  55,  29, 999,  47],
       [  3,  26,  59,  15,   0]])

In [30]:
array = np.random.randint(30, size=(4,5))
array

array([[28, 15,  9, 19, 18],
       [ 2, 18, 15,  5, 29],
       [ 3,  0, 28, 25, 11],
       [24, 27, 10,  1, 12]])

In [31]:
alt = array[1:3, 1:4].copy()
alt

array([[18, 15,  5],
       [ 0, 28, 25]])

In [45]:
alt

array([[ 18,  15,   5],
       [  0, 255,  25]])