# Array Ayırma (Splitting)

In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3,88,88,3,2,1])

In [3]:
np.split(x, [3,5])
# birinci parametre: ayrılacak dizi
# ikinci parametre: bir liste içerisinde diziyi hangi indexlerden bölmesi gerektiği

[array([1, 2, 3]), array([88, 88]), array([3, 2, 1])]

In [4]:
# diziyi böldüğümüzde yeni oluşan dizileri bir değişkene atayabiliriz

In [5]:
a,b,c = np.split(x, [3,5])

In [6]:
a

array([1, 2, 3])

In [7]:
b

array([88, 88])

In [8]:
c

array([3, 2, 1])

In [9]:
m = np.array([4,4,4,5,5,5,6,6,6,6,7,7,7,7,7])

In [10]:
np.split(m, [3,6,10])

[array([4, 4, 4]),
 array([5, 5, 5]),
 array([6, 6, 6, 6]),
 array([7, 7, 7, 7, 7])]

In [11]:
d,f,g,h = np.split(m, [3,6,10])

In [12]:
d

array([4, 4, 4])

In [13]:
f

array([5, 5, 5])

In [14]:
g

array([6, 6, 6, 6])

In [15]:
h

array([7, 7, 7, 7, 7])

In [16]:
# iki boyutlu diziyi ayırma

In [17]:
m = np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [18]:
np.vsplit(m, [2])
# burada verdiğimiz 2 değeri [ 8,  9, 10, 11] bu listeyi temsil ediyor.
# vsplit fonksiyonu ile yatay düzlemde bölme yaptık

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [19]:
ust, alt = np.vsplit(m, [2])

In [20]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [21]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [22]:
np.hsplit(m, [2])
# burada verdiğimiz 2 değeri dizinin 2. indexlerine denk geliyor
# hsplit fonksiyonu ile dikey düzlemde bölme yaptık

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [23]:
sag, sol = np.hsplit(m, [2])

In [24]:
sag

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [25]:
sol

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [26]:
my_array1 = np.arange(10)
my_array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
np.split(my_array1, [3])

[array([0, 1, 2]), array([3, 4, 5, 6, 7, 8, 9])]

In [28]:
np.split(my_array1, [8])

[array([0, 1, 2, 3, 4, 5, 6, 7]), array([8, 9])]

In [29]:
my_array2 = np.random.randint(17, size=(4,4))
my_array3 = np.random.randint(17, size=(4,4))
birlestir = np.concatenate([my_array2, my_array3])
ayirma = np.split(birlestir, [3])
ayirma2 = np.split(birlestir, [3], axis=1)

In [30]:
birlestir

array([[ 2, 10, 14, 10],
       [ 9,  3, 10,  6],
       [12,  6,  7, 12],
       [13, 16, 11,  7],
       [ 5, 13,  9, 11],
       [ 0,  2,  2,  7],
       [ 2,  8, 14,  3],
       [ 1,  4, 10,  1]])

In [31]:
ayirma

[array([[ 2, 10, 14, 10],
        [ 9,  3, 10,  6],
        [12,  6,  7, 12]]),
 array([[13, 16, 11,  7],
        [ 5, 13,  9, 11],
        [ 0,  2,  2,  7],
        [ 2,  8, 14,  3],
        [ 1,  4, 10,  1]])]

In [32]:
ayirma2

[array([[ 2, 10, 14],
        [ 9,  3, 10],
        [12,  6,  7],
        [13, 16, 11],
        [ 5, 13,  9],
        [ 0,  2,  2],
        [ 2,  8, 14],
        [ 1,  4, 10]]),
 array([[10],
        [ 6],
        [12],
        [ 7],
        [11],
        [ 7],
        [ 3],
        [ 1]])]

In [33]:
my_array = np.arange(0, 30, 3)
my_array

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [34]:
np.split(my_array, [2])

[array([0, 3]), array([ 6,  9, 12, 15, 18, 21, 24, 27])]

In [35]:
np.split(my_array, [2,4])

[array([0, 3]), array([6, 9]), array([12, 15, 18, 21, 24, 27])]

In [36]:
x = [1, 2, 3, 55, 66, 77, 88, 99]

In [37]:
np.split(x, [3,5])

[array([1, 2, 3]), array([55, 66]), array([77, 88, 99])]

In [38]:
np.split(x, [1, 2])

[array([1]), array([2]), array([ 3, 55, 66, 77, 88, 99])]

In [39]:
x, y, z = np.split(x, [1, 2])

In [40]:
x

array([1])

In [41]:
y

array([2])

In [42]:
z

array([ 3, 55, 66, 77, 88, 99])

In [44]:
split = np.arange(20).reshape(5,4)
split

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [45]:
np.vsplit(split, [2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])]

In [55]:
ust, alt = np.vsplit(split, [2])

In [56]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [57]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [63]:
split = np.random.randint(20, size=(4,4))
split

array([[17, 18,  4,  5],
       [ 0,  3, 11,  3],
       [ 7, 18,  0,  8],
       [ 0, 12,  7, 10]])

In [64]:
np.hsplit(split, [2])

[array([[17, 18],
        [ 0,  3],
        [ 7, 18],
        [ 0, 12]]),
 array([[ 4,  5],
        [11,  3],
        [ 0,  8],
        [ 7, 10]])]

In [65]:
sol, sag = np.hsplit(split, [2])

In [66]:
sol

array([[17, 18],
       [ 0,  3],
       [ 7, 18],
       [ 0, 12]])

In [67]:
sag

array([[ 4,  5],
       [11,  3],
       [ 0,  8],
       [ 7, 10]])