# Array Birleştirme (Concatenation)

In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [3]:
np.concatenate([x, y])

array([1, 2, 3, 4, 5, 6])

In [4]:
# bu method ile bir array dizisine sonradan dizi eklemesi yapabiliriz.

In [5]:
z = np.array([7,8,9])

In [6]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
g = np.concatenate([x,y])
g

array([1, 2, 3, 4, 5, 6])

In [8]:
np.concatenate([g, z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
# iki boyutlu diziler üzerinde birleştirme

In [10]:
a = np.array([[1,2,3],
              [4,5,6]])
# fonksiyon kullanmadan 2 boyutlu array oluşturduk

In [11]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
np.concatenate([a, a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [13]:
# axis parametresini kullanmadan 2 boyutlu iki diziyi birleştirirsek;
# concatenate fonksiyonuna verilen 2. dizi 1. dizinin üzerine eklenir.
# default olarak axis değeri 0 olduğu için satır sayısı artar. Sütun sayısı sabit kalır.

In [14]:
# axis değerini 1 olarak belirtelim.
np.concatenate([a, a], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [15]:
# axis=1 değeri için sütun sayısına ekleme yapıldı. satır sayısı sabit kaldı

In [16]:
c = np.array([3,4,5])
d = np.array([6,7,8])

np.concatenate([c,d])

array([3, 4, 5, 6, 7, 8])

In [17]:
n = np.array([[2,3,4],
             [5,6,7]])

m = np.array([[3,2,11],
             [5,9,0]])

np.concatenate([n,m])


array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 3,  2, 11],
       [ 5,  9,  0]])

In [18]:
np.concatenate([n,m], axis=1)

array([[ 2,  3,  4,  3,  2, 11],
       [ 5,  6,  7,  5,  9,  0]])

In [19]:
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])
my_array = np.concatenate([array1, array2])
my_array

array([1, 2, 3, 4, 5, 6])

In [20]:
array3 = np.random.randint(10, size=(3,3))
array4 = np.random.randint(10, size=(3,3))
my_array2 = np.concatenate([array3, array4])
my_array2

array([[3, 1, 6],
       [9, 5, 6],
       [2, 4, 6],
       [8, 5, 6],
       [8, 2, 9],
       [8, 0, 1]])

In [21]:
my_array3 = np.concatenate([array3, array4], axis = 1)
my_array3

array([[3, 1, 6, 8, 5, 6],
       [9, 5, 6, 8, 2, 9],
       [2, 4, 6, 8, 0, 1]])

In [22]:
my_array = np.random.randint(5, size=10)
my_array

array([4, 4, 4, 2, 3, 4, 4, 1, 4, 2])

In [23]:
my_array2 = np.random.randint(10, size=10)
my_array2

array([4, 2, 0, 5, 5, 4, 8, 8, 0, 8])

In [24]:
add =np.concatenate([my_array, my_array2])
add

array([4, 4, 4, 2, 3, 4, 4, 1, 4, 2, 4, 2, 0, 5, 5, 4, 8, 8, 0, 8])

In [25]:
sorting = np.sort(add)
sorting

array([0, 0, 1, 2, 2, 2, 3, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 8, 8, 8])

In [27]:
x = np.arange(1, 8)
y = np.arange(5, 15, 2)
array = np.concatenate([x, y])
array

array([ 1,  2,  3,  4,  5,  6,  7,  5,  7,  9, 11, 13])

In [28]:
z = [100, 200, 300, 400, 500]
np.concatenate([array, z])

array([  1,   2,   3,   4,   5,   6,   7,   5,   7,   9,  11,  13, 100,
       200, 300, 400, 500])

In [34]:
array = np.random.randint(20, size=(4,4))

In [35]:
array

array([[18,  8, 13, 11],
       [ 2,  3,  5,  5],
       [ 6,  6,  1, 14],
       [ 6,  5,  7,  0]])

In [36]:
array2 = np.random.randint(10, size=(4,4))

In [37]:
array2

array([[9, 3, 0, 9],
       [9, 6, 7, 0],
       [8, 2, 5, 3],
       [1, 6, 0, 6]])

In [41]:
np.concatenate([array, array2], axis=1)

array([[18,  8, 13, 11,  9,  3,  0,  9],
       [ 2,  3,  5,  5,  9,  6,  7,  0],
       [ 6,  6,  1, 14,  8,  2,  5,  3],
       [ 6,  5,  7,  0,  1,  6,  0,  6]])

In [42]:
my_array1 = np.random.randint(40, size=(4,4))
my_array2 = np.random.randint(60, size=(4,4))

In [43]:
np.concatenate([my_array, my_array2])

array([[ 1, 26, 13,  6],
       [10, 21, 36,  3],
       [18, 10, 36, 32],
       [ 1, 27, 36, 16],
       [40, 12, 24, 21],
       [17, 58, 23, 36],
       [39, 36, 27, 46],
       [20, 37, 58, 38]])

In [44]:
deneme1 = np.random.randint(20, size=(2,3))
deneme2 = np.random.randint(10, size=(2,2))
np.concatenate([deneme1, deneme2])

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 2