# Array Sıralama (Sorting)

In [1]:
import numpy as np

In [2]:
v = np.array([1,5,3,2,6,7,8,6,12,55,32])

In [3]:
np.sort(v)
# np.sort() komutu değişkenin kimyasını bozmaz

array([ 1,  2,  3,  5,  6,  6,  7,  8, 12, 32, 55])

In [4]:
v

array([ 1,  5,  3,  2,  6,  7,  8,  6, 12, 55, 32])

In [5]:
v.sort()
# fakat sort methodunu v.sort() olarak kullandığımızda değişkenin kimyası bozuldu

In [6]:
v

array([ 1,  2,  3,  5,  6,  6,  7,  8, 12, 32, 55])

In [7]:
# iki boyutlu array siralama

In [8]:
np.random.normal(20,5, (3,3))
# birinci parametre(20): standart sapmasının oranı
# ikinci parametre(5): dizinin ortalama oranı
# ücüncü parametre((3,3)): matris'in satır ve sütun sayısı

array([[19.28933333, 24.14109456, 18.10245698],
       [20.13590626, 19.99804775, 15.71850029],
       [22.23661252, 13.44503527, 14.27114623]])

In [9]:
a = np.random.normal(20, 5, (3,3))

In [10]:
a

array([[27.5832623 , 11.75153691, 23.10389402],
       [18.43879618, 18.31013669, 14.58147789],
       [23.99069958, 20.29482694, 21.59320472]])

In [11]:
np.sort(a, axis=1)
# satırlar arasında sıralama yapıldı

array([[11.75153691, 23.10389402, 27.5832623 ],
       [14.58147789, 18.31013669, 18.43879618],
       [20.29482694, 21.59320472, 23.99069958]])

In [12]:
np.sort(a, axis=0)
# sütunlar arasında sıralama yapıldı

array([[18.43879618, 11.75153691, 14.58147789],
       [23.99069958, 18.31013669, 21.59320472],
       [27.5832623 , 20.29482694, 23.10389402]])

In [13]:
my_array1 = np.random.randint(20, size=(1, 20))

In [14]:
my_array1

array([[19,  8,  5,  1,  9, 17, 18,  6, 12, 11, 16,  4, 16, 11, 15, 15,
         4,  2, 14, 17]])

In [15]:
sorting = np.sort(my_array1)
sorting

array([[ 1,  2,  4,  4,  5,  6,  8,  9, 11, 11, 12, 14, 15, 15, 16, 16,
        17, 17, 18, 19]])

In [16]:
my_array2 = np.random.randint(20, size=(5,5))
my_array2

array([[11,  7,  8,  1,  9],
       [ 0, 17,  7,  3, 17],
       [ 5,  4,  5, 15,  8],
       [17, 19, 19, 18,  1],
       [17, 15, 11, 14, 15]])

In [17]:
np.sort(my_array2, axis=0)
# her kolonu kendi içerisinde sıraladı.

array([[ 0,  4,  5,  1,  1],
       [ 5,  7,  7,  3,  8],
       [11, 15,  8, 14,  9],
       [17, 17, 11, 15, 15],
       [17, 19, 19, 18, 17]])

In [18]:
np.sort(my_array2, axis=1)
# her satırı kendi içerisinde sıraladı

array([[ 1,  7,  8,  9, 11],
       [ 0,  3,  7, 17, 17],
       [ 4,  5,  5,  8, 15],
       [ 1, 17, 18, 19, 19],
       [11, 14, 15, 15, 17]])

In [19]:
my_list = [10, 15, 37, 58, 65, 102]
my_list[0]

10

In [21]:
array = np.random.randint(20, size=8)
array

array([18,  7, 16,  9,  9,  4,  9, 10])

In [22]:
np.sort(array)

array([ 4,  7,  9,  9,  9, 10, 16, 18])

In [26]:
array = np.random.randint(30, size=(4,4))
array

array([[ 4, 18,  6,  6],
       [29,  0,  8,  7],
       [19, 13, 29,  2],
       [18, 25,  5,  4]])

In [27]:
np.sort(array, axis=0)

array([[ 4,  0,  5,  2],
       [18, 13,  6,  4],
       [19, 18,  8,  6],
       [29, 25, 29,  7]])

In [28]:
np.sort(array, axis=1)

array([[ 4,  6,  6, 18],
       [ 0,  7,  8, 29],
       [ 2, 13, 19, 29],
       [ 4,  5, 18, 25]])