# Fancy Index İle Elemanlara Erişmek

In [1]:
import numpy as np

In [2]:
v = np.arange(0, 30, 3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [3]:
[v[1], v[3], v[5], v[7]]

[3, 9, 15, 21]

In [4]:
index_listesi = [1,3,5]

In [5]:
v[index_listesi]

array([ 3,  9, 15])

In [6]:
# Yukarıda görüldüğü üzere elimizde büyük bir index listesi varsa ve binlerce veri arasından bu indexlere karşılık
# gelen verileri yakalamak istersek fancy index methodunu kullanabiliriz.

In [7]:
m = np.random.randint(20, size=(4,5))
m

array([[16,  1,  2, 10,  7],
       [10, 13,  6,  2,  1],
       [16,  3, 14,  1,  2],
       [12,  8,  2, 10, 18]])

In [8]:
satir = [1,3]
sutun = [2,3]
m[satir,sutun]

array([ 6, 10])

In [9]:
n = np.random.randint(20, size=(5,4))
n

array([[13, 12,  3, 15],
       [ 1,  8, 10,  2],
       [ 3,  2, 10, 16],
       [19,  0, 17, 17],
       [ 8,  6, 19, 18]])

In [10]:
n[0:, [1,2]]

array([[12,  3],
       [ 8, 10],
       [ 2, 10],
       [ 0, 17],
       [ 6, 19]])

In [11]:
my_array = np.arange(0,50, 5)
my_array

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [12]:
my_array[[2,3,4]]

array([10, 15, 20])

In [13]:
my_array[[4,5,6]]

array([20, 25, 30])

In [32]:
fancy = np.random.randint(40, size=(5,5))
fancy

array([[32,  9, 10,  0, 26],
       [34, 27,  0, 14, 16],
       [ 4, 24, 18, 17, 17],
       [15, 35, 25, 10, 38],
       [13, 21, 26, 31, 12]])

In [33]:
satir = [1,3]
sutun = [2,3]
fancy[satir, sutun]

array([ 0, 10])

In [34]:
satir = 3
sutun = [0, 3]
fancy[satir, sutun]

array([15, 10])

In [35]:
fancy[:,:]

array([[32,  9, 10,  0, 26],
       [34, 27,  0, 14, 16],
       [ 4, 24, 18, 17, 17],
       [15, 35, 25, 10, 38],
       [13, 21, 26, 31, 12]])

In [36]:
fancy[:,1]

array([ 9, 27, 24, 35, 21])

In [38]:
fancy[1:4, 2:4]

array([[ 0, 14],
       [18, 17],
       [25, 10]])

In [44]:
fancy[1:4, 2:5]

array([[ 0, 14, 16],
       [18, 17, 17],
       [25, 10, 38]])

In [45]:
fancy[[2,3], 2:]

array([[18, 17, 17],
       [25, 10, 38]])

In [46]:
fancy[1:, 2:]

array([[ 0, 14, 16],
       [18, 17, 17],
       [25, 10, 38],
       [26, 31, 12]])