# Find The Index

In [2]:
import numpy as np

In [3]:
my_array = np.random.randint(10, size=8)
my_array

array([1, 3, 4, 2, 8, 2, 1, 9])

In [4]:
np.where(my_array == 9)

(array([7], dtype=int64),)

In [5]:
np.where(my_array == 2)

(array([3, 5], dtype=int64),)

In [6]:
array = np.random.randint(20, size=10)
array

array([18,  1, 16,  3,  9, 16, 17, 12, 15,  4])

In [7]:
np.where(array == 18)

(array([0], dtype=int64),)

In [8]:
array = np.random.randint(20, size=(3,3))
array

array([[ 6,  3,  0],
       [ 6,  1, 18],
       [ 6, 12,  1]])

In [9]:
np.where(array == 1)

(array([1, 2], dtype=int64), array([1, 2], dtype=int64))

In [14]:
np.where(array == 6)

(array([0, 1, 2], dtype=int64), array([0, 0, 0], dtype=int64))

In [15]:
np.where(array == 12)

(array([2], dtype=int64), array([1], dtype=int64))

In [11]:
array2 = np.random.randint(10, size=10)
array2

array([6, 4, 2, 8, 3, 3, 5, 1, 7, 8])

In [12]:
np.where(array2 == 3)

(array([4, 5], dtype=int64),)

In [13]:
np.where(array2 == 8)

(array([3, 9], dtype=int64),)