# Index İle Elemanlara Erişmek

In [1]:
import numpy as np

In [2]:
a = np.random.randint(10, size=10)
a

array([5, 4, 5, 0, 4, 1, 7, 6, 2, 1])

In [3]:
a[5]

1

In [5]:
a[1]

4

In [6]:
a[-1]

1

In [7]:
a[:2]

array([5, 4])

In [8]:
a[2:]

array([5, 0, 4, 1, 7, 6, 2, 1])

In [10]:
a[:5]

array([5, 4, 5, 0, 4])

In [11]:
a[5:]

array([1, 7, 6, 2, 1])

In [12]:
a[0] = 100
a

array([100,   4,   5,   0,   4,   1,   7,   6,   2,   1])

In [14]:
my_array = np.random.randint(10, size=(3,5))
my_array

array([[4, 0, 5, 9, 9],
       [4, 6, 3, 1, 2],
       [2, 0, 7, 8, 3]])

In [15]:
my_array[0,0]

4

In [16]:
my_array[0,1]

0

In [18]:
my_array[1,0]

4

In [19]:
my_array[2,1]

0

In [20]:
my_array[2, 2]

7

In [21]:
my_array

array([[4, 0, 5, 9, 9],
       [4, 6, 3, 1, 2],
       [2, 0, 7, 8, 3]])

In [23]:
my_array[2, 3] = 122

In [24]:
my_array

array([[  4,   0,   5,   9,   9],
       [  4,   6,   3,   1,   2],
       [  2,   0,   7, 122,   3]])

In [26]:
my_array[1, 2] = 59.34

In [27]:
my_array

array([[  4,   0,   5,   9,   9],
       [  4,   6,  59,   1,   2],
       [  2,   0,   7, 122,   3]])

In [28]:
my_array[1, 2]

59