# Matematiksel İşlemler

In [1]:
import numpy as np

In [3]:
v = np.array([1,2,3,4,5])
v

array([1, 2, 3, 4, 5])

In [4]:
v - 1

array([0, 1, 2, 3, 4])

In [5]:
v + 1

array([2, 3, 4, 5, 6])

In [6]:
v * 5

array([ 5, 10, 15, 20, 25])

In [7]:
v / 10

array([0.1, 0.2, 0.3, 0.4, 0.5])

In [8]:
# yukarıda bir dizinin elemanlarını kolayca matematiksel bir işleme tabi tutabiliyoruz.
# biz numpy 'a bir işlem yaptırmak istediğimizde arka tarafta aslında aşağıdaki fonksiyonlar çalışır.

In [10]:
np.subtract(v, 1)

array([0, 1, 2, 3, 4])

In [11]:
np.add(v, 5)

array([ 6,  7,  8,  9, 10])

In [12]:
np.multiply(v, 3)

array([ 3,  6,  9, 12, 15])

In [13]:
np.divide(v, 10)

array([0.1, 0.2, 0.3, 0.4, 0.5])

In [14]:
np.power(v, 2)

array([ 1,  4,  9, 16, 25], dtype=int32)

In [15]:
np.mod(v, 3)

array([1, 2, 0, 1, 2], dtype=int32)

In [17]:
np.absolute(-3)
# absolute methodu mutlak değer almak için kullanılır

3

In [22]:
np.absolute(9)

9

In [29]:
np.sin(360)
# verilen parametrenin sinus değeri hesaplanır

0.9589157234143065

In [30]:
np.cos(180)
# verilen parametrenin cosinüs değeri hesaplanır

-0.5984600690578581

In [31]:
np.tan(270)
# verilen parametrenin tanjant değeri hesaplanır.

-0.17883906379845224

In [32]:
np.log(v)
# verilen parametrenin logaritması hesaplanır

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [33]:
np.log2(v)
# verilen parametrenin 2. dereceden logaritması hesaplanır

array([0.        , 1.        , 1.5849625 , 2.        , 2.32192809])

In [34]:
np.log10(v)
# verilen parametrenin 10. dereceden logaritması hesaplanır.

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ])

In [35]:
#cheatsheet. derli toplu dökümantasyon