In [73]:
# Numpy Array'i Oluşturmak

In [74]:
import numpy as np

In [75]:
# Normal listeler kullandıldığında liste içerisindeki her bir eleman ön bellekte yer kaplar. Fakat Numpy dizileri kullanıldığı zaman numpy dizisi 1 birim yer kaplar. Büyük bir tasarruf sağlanmış olunur.

In [76]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [77]:
a = np.array([1,2,3,4,5])

In [78]:
type(a)

numpy.ndarray

In [79]:
np.array([3.14, 4, 12, 18]) #Numpy dizileri, verileri tek tip olmaya zorlar.

array([ 3.14,  4.  , 12.  , 18.  ])

In [80]:
np.array([3.14, 4, 12, 18], dtype="float32") # Numpy dizimiz float olmaya zorlandı

array([ 3.14,  4.  , 12.  , 18.  ], dtype=float32)

In [81]:
np.array([3.14, 4, 12, 18], dtype="int") # Numpy dizimiz integer olmaya zorlandı.

array([ 3,  4, 12, 18])

In [82]:
# sifirdaan array oluşturma

In [83]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [84]:
np.zeros(10, dtype=float)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [85]:
np.ones((2, 3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [86]:
np.ones((3, 8), dtype=int)

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [87]:
np.ones((2,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [88]:
np.full((2,5), 3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [89]:
np.full((2,4), 9, dtype=int)

array([[9, 9, 9, 9],
       [9, 9, 9, 9]])

In [90]:
np.full((5, 4), 15, dtype=float)

array([[15., 15., 15., 15.],
       [15., 15., 15., 15.],
       [15., 15., 15., 15.],
       [15., 15., 15., 15.],
       [15., 15., 15., 15.]])

In [91]:
np.arange(0, 30, 5)

array([ 0,  5, 10, 15, 20, 25])

In [92]:
np.arange(5, 101, 10)

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [93]:
# linspace parametresini kullanarak standart sapma hesaplaması yapmak için veri üretilebilir!

In [94]:
np.linspace(0,1 ,6)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [95]:
np.linspace(5, 10, 15)

array([ 5.        ,  5.35714286,  5.71428571,  6.07142857,  6.42857143,
        6.78571429,  7.14285714,  7.5       ,  7.85714286,  8.21428571,
        8.57142857,  8.92857143,  9.28571429,  9.64285714, 10.        ])

In [96]:
np.linspace(10,11, 20)

array([10.        , 10.05263158, 10.10526316, 10.15789474, 10.21052632,
       10.26315789, 10.31578947, 10.36842105, 10.42105263, 10.47368421,
       10.52631579, 10.57894737, 10.63157895, 10.68421053, 10.73684211,
       10.78947368, 10.84210526, 10.89473684, 10.94736842, 11.        ])

In [97]:
# tek boyutlu array 'in karşılığı vektördür.
# iki boyutlu array 'in karşılığı matrisdir.

In [98]:
# dizinin istediğimiz ortalama ve standart sapma değerlerini girerek bir dizi oluşturabiliriz

In [99]:
np.random.normal(10, 5, (3,4))
# birinci parametre: dizi ortalaması
# ikinci parametre: standart sapması
# üçüncü parametre: kolon ve satır sayısı

array([[13.87239583, 13.37232826, 16.56761497, 13.34437372],
       [13.60444297, 15.39617977, 10.47396505, 13.37091839],
       [11.14439708,  9.67127576, 13.45192929, 10.90757765]])

In [100]:
np.random.randint(0, 21, (3,3))
# birinci parametre: başlangıç değeri
# ikinci parametre: bitiş değeri (dahil değil)
# üçüncü parametre: kolon ve satır sayısı

array([[ 6, 18, 16],
       [20, 13,  1],
       [ 5, 18, 10]])

In [101]:
my_array = np.array([1, 2, 3.10, 'murat'])

print(my_array)

['1' '2' '3.1' 'murat']


In [102]:
np.array([1, 2, 3, 5.19, 12.67])

array([ 1.  ,  2.  ,  3.  ,  5.19, 12.67])

In [103]:
print([1,2,3,4, 'murat', 'numpy', 25.09, 255.57])

[1, 2, 3, 4, 'murat', 'numpy', 25.09, 255.57]


In [104]:
np.array([2, 3, 5.5, 28.71, 93.16])

array([ 2.  ,  3.  ,  5.5 , 28.71, 93.16])

In [105]:
np.array([1, 2, 3.14, 'murat', 'cengiz'])

array(['1', '2', '3.14', 'murat', 'cengiz'], dtype='<U32')

In [106]:
np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]])


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [107]:
np.arange(3, 14, 2)

array([ 3,  5,  7,  9, 11, 13])

In [108]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [109]:
np.linspace(10, 100, num=11)

array([ 10.,  19.,  28.,  37.,  46.,  55.,  64.,  73.,  82.,  91., 100.])

In [110]:
np.linspace(10, 25, num=4)

array([10., 15., 20., 25.])

In [111]:
np.random.normal(5, 10, 5)

array([ 6.76407574, -5.09528395, 18.24833294, 14.32104595, 11.57599403])

In [112]:
np.random.normal(5, 9, 6)

array([  2.33490447,  15.21350812,  19.07080799,   7.76180333,
       -14.65229659,  18.9058373 ])

In [113]:
np.random.normal(15, 3, 5)

array([16.22816795, 11.05893333, 14.44115222, 16.65098166, 11.31349899])

In [114]:
np.random.normal(20, 2, (3,3))

array([[19.86835654, 20.41158119, 22.3525017 ],
       [20.00197859, 19.08258013, 22.37255026],
       [19.72099846, 23.02665205, 16.13347226]])

In [115]:
np.random.normal(50, 1, (5,4))

array([[49.6087657 , 49.75006892, 50.27382821, 49.67349186],
       [50.32825233, 50.79958943, 50.16939071, 50.59032096],
       [51.03144206, 49.7728819 , 49.72638224, 50.2745548 ],
       [49.16041109, 48.79190593, 51.64191581, 50.41412495],
       [50.12437685, 49.64252197, 50.4084079 , 50.36220951]])

In [116]:
my_string = "murat"
my_string[0]

'm'

In [117]:
my_string[1]

'u'

In [118]:
my_list = ['murat', 'cengiz']
my_list[1]

'cengiz'