# Slicing İle Elemanlara Erişmek (Array Alt Kümesine Erişmek)

In [1]:
import numpy as np

In [2]:
my_array = np.arange(30, 40)
my_array

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [3]:
my_array[1:4]

array([31, 32, 33])

In [4]:
my_array[2:5]

array([32, 33, 34])

In [5]:
my_array[5:9]

array([35, 36, 37, 38])

In [6]:
np.size(my_array)

10

In [7]:
np.ndim(my_array)

1

In [8]:
np.shape(my_array)

(10,)

In [9]:
my_array.dtype

dtype('int32')

In [10]:
my_array = np.random.randint(30, size=(3,3))
my_array

array([[13,  5,  4],
       [28, 28, 22],
       [27, 16, 10]])

In [11]:
my_array[1]

array([28, 28, 22])

In [12]:
my_array[2]

array([27, 16, 10])

In [13]:
my_array[1, :]

array([28, 28, 22])

In [14]:
my_array[1,2]

22

In [15]:
my_array[2, 2]

10

In [16]:
my_array[0, 2]

4

In [17]:
my_array[1, 1:]

array([28, 22])

In [18]:
my_array[2, 1:]

array([16, 10])

In [19]:
my_array2 = np.random.randint(20, size = (5,5))
my_array2

array([[ 7, 12,  6,  6,  7],
       [16, 11,  4,  4,  9],
       [19,  5, 18,  0, 18],
       [18,  3,  9,  0,  7],
       [ 5, 12, 10, 12, 11]])

In [20]:
my_array2[1]

array([16, 11,  4,  4,  9])

In [21]:
my_array2[1, 1:]

array([11,  4,  4,  9])

In [22]:
my_array2[2:, 2]

array([18,  9, 10])

In [23]:
my_array2[3:, 3:]

array([[ 0,  7],
       [12, 11]])

In [24]:
my_array2[3:, 1:4]

array([[ 3,  9,  0],
       [12, 10, 12]])

In [25]:
my_array2[:2, 1:4]

array([[12,  6,  6],
       [11,  4,  4]])

In [26]:
my_array2[:3, 1:4]

array([[12,  6,  6],
       [11,  4,  4],
       [ 5, 18,  0]])

In [27]:
my_array3 = np.random.randint(50, size=(8,8))
my_array3

array([[44, 28, 48,  4,  9, 34, 48, 15],
       [15, 37, 45, 26, 16,  0, 28,  0],
       [31, 40, 35, 19,  1,  2,  3, 44],
       [45, 41, 16, 33, 36, 25,  3, 41],
       [19, 16, 17, 48, 49, 11, 11, 48],
       [43, 23, 25, 12, 18,  6, 16, 48],
       [35, 45, 40, 12, 32, 22,  3, 19],
       [ 6, 13, 15, 31, 30, 20,  7, 45]])

In [28]:
my_array3[2:7, 1:7]

array([[40, 35, 19,  1,  2,  3],
       [41, 16, 33, 36, 25,  3],
       [16, 17, 48, 49, 11, 11],
       [23, 25, 12, 18,  6, 16],
       [45, 40, 12, 32, 22,  3]])

In [29]:
my_array3[6:,:]

array([[35, 45, 40, 12, 32, 22,  3, 19],
       [ 6, 13, 15, 31, 30, 20,  7, 45]])

In [30]:
my_array3[5:7,4:6]

array([[18,  6],
       [32, 22]])

In [31]:
my_array3[0, :]

array([44, 28, 48,  4,  9, 34, 48, 15])

In [32]:
my_array3[:,0]

array([44, 15, 31, 45, 19, 43, 35,  6])

In [33]:
my_array = np.arange(0, 20, 2)
my_array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [34]:
my_array[1:7:2]

array([ 2,  6, 10])

In [35]:
deneme = np.arange(0,5)
deneme

array([0, 1, 2, 3, 4])

In [36]:
deneme.view()

array([0, 1, 2, 3, 4])

In [37]:
my_list = np.arange(1, 15)
my_list

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [38]:
my_slicing1 = my_list[0:3]
my_slicing1

array([1, 2, 3])

In [39]:
my_slicing2 = my_list[3:6]
my_slicing2

array([4, 5, 6])

In [40]:
my_slicing3 = my_list[6:9]
my_slicing3

array([7, 8, 9])

In [41]:
my_slicing4 = my_list[9:12]
my_slicing4

array([10, 11, 12])

In [42]:
my_slicing5 = my_list[12:14]
my_slicing5

array([13, 14])

In [43]:
my_slicing6 = my_list[0:10:2]
my_slicing6

array([1, 3, 5, 7, 9])

In [44]:
my_slicing7 = my_list[1:10:2]
my_slicing7

array([ 2,  4,  6,  8, 10])

In [45]:
my_list2 = np.random.randint(20, size=(5,5))
my_list2

array([[ 2,  6,  0, 15,  5],
       [14, 10,  3, 14, 12],
       [14,  7, 10, 16,  2],
       [17, 16, 13, 16, 19],
       [ 0,  9, 14,  4,  4]])

In [46]:
parca = my_list2[[1],[1]]
parca

array([10])

In [47]:
parca1 = my_list2[1:3]
parca1

array([[14, 10,  3, 14, 12],
       [14,  7, 10, 16,  2]])

In [48]:
parca2 = my_list2[[1,3]]
parca2

array([[14, 10,  3, 14, 12],
       [17, 16, 13, 16, 19]])

In [49]:
parca3 = my_list2[1:2, 2:3]
parca3

array([[3]])

In [50]:
parca4 = my_list2[0:3, 1:4]
parca4

array([[ 6,  0, 15],
       [10,  3, 14],
       [ 7, 10, 16]])

In [51]:
my_list2

array([[ 2,  6,  0, 15,  5],
       [14, 10,  3, 14, 12],
       [14,  7, 10, 16,  2],
       [17, 16, 13, 16, 19],
       [ 0,  9, 14,  4,  4]])

In [52]:
my_list3 = np.sort(my_list2)
my_list3

array([[ 0,  2,  5,  6, 15],
       [ 3, 10, 12, 14, 14],
       [ 2,  7, 10, 14, 16],
       [13, 16, 16, 17, 19],
       [ 0,  4,  4,  9, 14]])

In [53]:
my_list3[0,1]

2

In [54]:
my_list3[0:1]

array([[ 0,  2,  5,  6, 15]])

In [55]:
my_list3[0,2]

5

In [56]:
my_list3[0:2]

array([[ 0,  2,  5,  6, 15],
       [ 3, 10, 12, 14, 14]])

In [57]:
my_list3[1:2]

array([[ 3, 10, 12, 14, 14]])

In [58]:
my_list3[1:2, 3:5]

array([[14, 14]])

In [59]:
slicing = [1,2,3,4,5,6,7,8]
slicing[0:4]

[1, 2, 3, 4]

In [60]:
my_list = [1, 2, 3, 4, 5, 6]
my_list[1:]

[2, 3, 4, 5, 6]

In [61]:
slicing = [1, 2, 3, 4, 5, 6]
slicing[:5]

[1, 2, 3, 4, 5]

In [62]:
slicing = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]

slicing[-3]

11

In [63]:
slicing = np.random.randint(20, size=(4,5))
slicing

array([[ 6,  6, 14,  0, 14],
       [16,  0, 13, 14,  3],
       [ 1,  9,  9,  9, 17],
       [14,  6,  7,  2,  9]])

In [64]:
slicing[-1,-1]

9

In [66]:
my_slicing = np.random.randint(20, size=(5,4))
my_slicing

array([[ 5, 19,  0, 11],
       [10,  2, 17,  3],
       [ 9,  8, 10, 12],
       [ 6, 12, 10,  1],
       [14,  5, 17, 13]])

In [67]:
my_slicing[1:3, 1:3]

array([[ 2, 17],
       [ 8, 10]])

In [68]:
my_slicing[3, 1:4]

array([12, 10,  1])

In [70]:
slicing = np.random.randint(100, size=(10, 10))
slicing

array([[ 2, 36, 91, 91, 43, 66,  2, 12, 96, 22],
       [43, 78, 79, 35, 70, 68, 90, 84, 90, 42],
       [40,  2,  7, 64, 80, 37, 14, 16, 64, 95],
       [46, 43, 58, 17, 60, 46, 95, 77, 29, 76],
       [61, 61, 30,  5, 95, 53, 11, 43,  4, 76],
       [42, 12, 40, 44, 33,  4, 60, 27, 98, 68],
       [ 9, 78, 44, 95, 93, 19, 94, 77, 84, 11],
       [60, 26, 45, 95, 95, 52, 57, 16, 42, 43],
       [74, 84, 33, 84,  3, 68, 60, 34, 48, 59],
       [81, 22, 32, 14, 31, 69, 52,  1, 37, 30]])

In [71]:
slicing[1:3]

array([[43, 78, 79, 35, 70, 68, 90, 84, 90, 42],
       [40,  2,  7, 64, 80, 37, 14, 16, 64, 95]])

In [72]:
slicing[1:5, 2:4]

array([[79, 35],
       [ 7, 64],
       [58, 17],
       [30,  5]])

In [73]:
slicing[6:9, 6:9]

array([[94, 77, 84],
       [57, 16, 42],
       [60, 34, 48]])