In [1]:
import numpy as np

In [2]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
a = np.arange(1, 10)

In [4]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
a.ndim

1

In [6]:
b = a.reshape((1,9))

In [7]:
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [8]:
b.ndim

2

In [9]:
# Bazı numpy fonksiyonlarını kullanabilmek adına bir vektörü matris 'e çevirmemiz gerekebilir. Bu tarz durumlarda reshape methodu işimize yarayabilir. 1 satırdan oluşan bir vektörü matris 'e dönüştürebiliriz.

In [10]:
c = a.reshape((3,3))

In [11]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
# Bir vektörü matris 'e çevirebiliriz
# Bir matris'i isteğimize göre şekillendirebiliriz.

In [13]:
v = np.arange(20)

In [14]:
v

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [15]:
v.ndim

1

In [16]:
v.size

20

In [17]:
v.dtype

dtype('int32')

In [18]:
v.shape

(20,)

In [19]:
v.reshape((4,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [20]:
v.reshape((5,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [21]:
my_shape = np.arange(0, 10)
my_shape

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
my_shape.reshape(-1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
shape = np.random.randint(20 , size=(5, 4))


In [24]:
shape

array([[ 8, 16,  4, 13],
       [15, 18, 13, 16],
       [ 0,  1, 12, 15],
       [ 4, 14,  8, 18],
       [12, 17, 19,  7]])

In [25]:
shape.reshape((4,5))

array([[ 8, 16,  4, 13, 15],
       [18, 13, 16,  0,  1],
       [12, 15,  4, 14,  8],
       [18, 12, 17, 19,  7]])

In [26]:
shape.reshape((10,2))

array([[ 8, 16],
       [ 4, 13],
       [15, 18],
       [13, 16],
       [ 0,  1],
       [12, 15],
       [ 4, 14],
       [ 8, 18],
       [12, 17],
       [19,  7]])

In [29]:
shape.reshape((8, 10))

ValueError: cannot reshape array of size 20 into shape (8,10)

In [28]:
shape.size

20